import fastify from "fastify";
import { registerRoutes } from "../tsp-output/src/router.js";
import type { Pets } from "../tsp-output/src/operations/pets.js";
import type { Pet, NewPet } from "../tsp-output/src/models/petstore.js";

// Example in-memory store
const pets: Pet[] = [
  { id: 1, name: "Fluffy", age: 3, species: "Cat" },
  { id: 2, name: "Buddy", age: 5, species: "Dog" },
];

let nextId = 3;

// Implement the operations interface generated by TypeSpec
const petsOperations: Pets = {
  async list(options) {
    const limit = options?.limit ?? pets.length;
    return {
      statusCode: 200,
      body: pets.slice(0, limit),
    };
  },

  async create(body) {
    const newPet: Pet = {
      id: nextId++,
      ...body,
    };
    pets.push(newPet);
    return {
      statusCode: 201,
      body: newPet,
    };
  },

  async get(petId) {
    const pet = pets.find(function findPet(p) {
      return p.id === petId;
    });
    if (!pet) {
      throw new Error(`Pet with id ${petId} not found`);
    }
    return {
      statusCode: 200,
      body: pet,
    };
  },

  async update(petId, body) {
    const index = pets.findIndex(function findPet(p) {
      return p.id === petId;
    });
    if (index === -1) {
      throw new Error(`Pet with id ${petId} not found`);
    }
    pets[index] = body;
    return {
      statusCode: 200,
      body: body,
    };
  },

  async delete(petId) {
    const index = pets.findIndex(function findPet(p) {
      return p.id === petId;
    });
    if (index === -1) {
      throw new Error(`Pet with id ${petId} not found`);
    }
    pets.splice(index, 1);
    return { statusCode: 204 };
  },
};

async function start() {
  // Create Fastify instance with your desired configuration
  const server = fastify({
    logger: true,
  });

  // Register the generated routes with your operation implementations
  await registerRoutes(server, {
    pets: petsOperations,
  });

  // Start the server
  try {
    await server.listen({ port: 3000, host: "0.0.0.0" });
    console.log("Server is running on http://localhost:3000");
  } catch (err) {
    server.log.error(err);
    process.exit(1);
  }
}

start();
